test_average (__main__.TestExercice) ... FAIL
test_square (__main__.TestExercice) ... ok
test_square_root (__main__.TestExercice) ... ok
test_to_celsius (__main__.TestExercice) ... FAIL
test_to_degrees (__main__.TestExercice) ... FAIL
test_to_farenheit (__main__.TestExercice) ... ok
test_to_radians (__main__.TestExercice) ... FAIL

======================================================================
FAIL: test_average (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 50, in test_average
    'Mauvais calcul de la moyenne'
AssertionError: Lists differ: [4.0, 4.0, 4.0] != [4.0, 0.0, -2.3333333333333335]

First differing element 1:
4.0
0.0

- [4.0, 4.0, 4.0]
+ [4.0, 0.0, -2.3333333333333335] : Mauvais calcul de la moyenne

======================================================================
FAIL: test_to_celsius (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 98, in test_to_celsius
    'Mauvais calcul de farenheit -> celsius'
AssertionError: Lists differ: [-17.77777777777778, -31.666666666666668, 232.7777777777778] != [-17.77777777777778, -31.666666666666664, 232.77777777777777]

First differing element 1:
-31.666666666666668
-31.666666666666664

- [-17.77777777777778, -31.666666666666668, 232.7777777777778]
?                                        ^                  ^

+ [-17.77777777777778, -31.666666666666664, 232.77777777777777]
?                                        ^                  ^^
 : Mauvais calcul de farenheit -> celsius

======================================================================
FAIL: test_to_degrees (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 86, in test_to_degrees
    'Mauvais calcul de radians -> degres'
AssertionError: Lists differ: [(114.59155902616465, 1.909859317102744, 0.[201 chars]852)] != [(79.0980174562859, 5.881047377154118, 29.6[197 chars]998)]

First differing element 0:
(114.59155902616465, 1.909859317102744, 0.03183098861837907)
(79.0980174562859, 5.881047377154118, 29.612494192724625)

- [(114.59155902616465, 1.909859317102744, 0.03183098861837907),
-  (-229.1831180523293, -3.819718634205488, -0.06366197723675814),
-  (286.4788975654116, 4.7746482927568605, 0.07957747154594767),
-  (234.3397382085067, 3.9056623034751117, 0.0650943717245852)]
+ [(79.0980174562859, 5.881047377154118, 29.612494192724625),
+  (-278.1960349125718, 48.23790524569176, 0.7750116145507491),
+  (257.74504364071475, -15.297381557114704, 44.031235481811564),
+  (213.95544569810457, -2.673258113725865, 23.057550624127998)] : Mauvais calcul de radians -> degres

======================================================================
FAIL: test_to_radians (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 67, in test_to_radians
    'Mauvais calcul de degres -> radians'
AssertionError: Lists differ: [-0.0[13 chars]503, 0.17598251810595045, 6.283490739798685, 6.997344948274799] != [-0.0[13 chars]503, 0.17598251810595048, 6.283490739798685, 6.9973449482748]

First differing element 1:
0.17598251810595045
0.17598251810595048

+ [-0.08668468618238503, 0.17598251810595048, 6.283490739798685, 6.9973449482748]
- [-0.08668468618238503,
-  0.17598251810595045,
-  6.283490739798685,
-  6.997344948274799] : Mauvais calcul de degres -> radians

----------------------------------------------------------------------
Ran 7 tests in 0.007s

FAILED (failures=4)
